name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      - run: flutter create. --project-name sewa_check_app --platforms=android --no-pub
      - run: flutter pub add url_launcher
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: sewa-check-app-apk
          path: build/app/outputs/flutter-apk/app-release.apk
